src/installies/models/base.py
from peewee import (
    Model,
    CharField,
    DateField,
    BooleanField,
    TextField,
    ForeignKeyField,
)
from installies.config import database, apps_path
from installies.lib.random import gen_random_id
from installies.lib.url import make_slug
from datetime import date

import json
import bcrypt
import os
import string
import random


class BaseModel(Model):
    """A base class that defines the default database for the models to use."""

    class Meta:
        """Meta data for the BaseModel."""

        database = database

src/installies/models/script.py
from peewee import (
    Model,
    CharField,
    TextField,
    DateTimeField,
    BooleanField,
    TextField,
    ForeignKeyField,
    JOIN,
)
from installies.models.base import BaseModel
from installies.models.user import User
from installies.models.app import App
from installies.models.maintainer import Maintainers
from installies.models.discussion import Thread
from installies.config import database, apps_path
from installies.lib.url import make_slug
from installies.lib.random import gen_random_id
from installies.lib.shell import Shell
from datetime import datetime

import json
import os
import string
import random
import bleach

class ScriptNotFound(Exception):
    """An exception to raise when an app cannot be found."""


class Script(BaseModel):
    """A model for storing data about scripts."""

    creation_date = DateTimeField(default=datetime.now)
    last_modified = DateTimeField(default=datetime.now)
    submitter = ForeignKeyField(User, backref='scripts')
    maintainers = ForeignKeyField(Maintainers)
    description = CharField(255)

    filepath = CharField(255)
    shell = CharField(255)
    use_default_function_matcher = BooleanField(default=True)

    version = CharField(64, null=True)
    
    app = ForeignKeyField(App, backref='scripts')
    thread = ForeignKeyField(Thread, backref='for_script')
    
    def open_content(self, mode='r'):
        """
        Get the content of the script.

        :param mode: The mode to open the content in.
        """
        return open(self.filepath, mode)

    @classmethod
    def create_script_file(cls, directory: str, content: str):
        """
        Create a file to store the data for the script.

        The path is returned.

        :param directory: The directory to put the script in.
        :param content: The content of the script.
        """
        script_filename = ''
        script_path = ''

        # since script file names are randomly generated there is a slight
        # chance that it generates the name of a script file that already
        # exists.
        while True:
            script_filename = f'script-{gen_random_id()}'

            script_path = os.path.join(directory, script_filename)

            if os.path.exists(script_path) is False:

                with open(script_path, 'w') as f:
                    f.write(content)

                break

        return script_path

    @classmethod
    def create(
            cls,
            content: str,
            description: str,
            shell: str,
            submitter: User,
            app,
            actions: list[str],
            version=None,
            use_default_function_matcher: bool=True,
    ):
        """
        Create a Script object, and adds it to the database.

        :param content: The content of the script.
        :param description: The script's description.
        :param shell: The name of the shell the script is for.
        :param submitter: The submitter.

        :param app: The app the script is of.
        :param actions: The actions that the script supports.
        :param version: The version of the app the script is for.
        :param use_default_function_matcher: A boolean to mark if the
            script uses the function to action matcher.
        """
        thread = Thread.create(
            title=f'Discussion of script: "{description}"',
            creator=None,
            app=app,
        )
        
        filepath = cls.create_script_file(apps_path, content)

        maintainers = Maintainers.create()
        
        created_script = super().create(
            maintainers=maintainers,
            submitter=submitter,
            filepath=filepath,
            description=description,
            shell=shell,
            app=app,
            version=version,
            use_default_function_matcher=use_default_function_matcher,
            thread=thread,
        )

        actions = Action.create_from_list(created_script, actions)

        maintainers.add_maintainer(submitter)

        return created_script

    def edit(
            self,
            content: str,
            description: str,
            shell: str,
            actions: list[str],
            version=None,
            use_default_function_matcher: bool=True,
    ):
        """
        Edits the script.

        :param content: The new content.
        :param method: The script's method.
        :param shell: The name of the shell the script is for.
        :param actions: The actions that the script supports.
        :param version: The version of the app the script is for.
        :param use_default_function_matcher: A boolean to mark if the
            script uses the function to action matcher.
        """

        self.thread.title = f'Discussion of script: "{description}"'
        self.thread.save()

        self.last_modified = datetime.today()

        self.description = description
        self.shell = shell

        self.version = version
        self.use_default_function_matcher = use_default_function_matcher
        self.save()

        with self.open_content('w') as f:
            f.write(content)

        Action.delete().where(Action.script == self).execute()
        Action.create_from_list(self, actions)

        self.save()

    def delete_instance(self):
        """Deletes the script and its related objects."""

        for script_report in self.reports:
            script_report.report.delete_instance()
        
        super().delete_instance()

        self.thread.delete_instance()
        
        os.remove(self.filepath)

    def serialize(self):
        """Turns the Script into a json serializable dict."""
        data = {}

        data['id'] = self.id
        data['shell'] = self.shell
        data['supported_distros'] = self.get_supported_distros_as_dict()
        data['creation_date'] = str(self.creation_date)
        data['last_modified'] = str(self.last_modified)
        
        with self.open_content() as c:
            data['content'] = c.read()
        
        data['submitter'] = self.submitter.username
        data['description'] = self.description

        data['actions'] = [action.name for action in self.actions]
        data['for_version'] = self.version
        data['content'] = self.complete_content()

        return data

    def can_user_edit(self, user: User):
        """
        Check if the given user is allowed to edit the script.
        """
        if user is None:
            return False

        if user.admin is True:
            return True

        if self.maintainers.is_maintainer(user):
            return True

        return False

    def get_supported_distros_as_dict(self) -> dict:
        """
        Puts all the script's distros in a dictionary.

        The keys are the distro's architechture, and the values are lists of distro names.
        """

        distros = {}

        for distro in self.supported_distros:
            if distro.architecture_name not in distros.keys():
                distros[distro.architecture_name] = []

            distros[distro.architecture_name].append(distro.distro_name)
            
        return distros

    def get_supported_distros_as_string(self):
        """
        Turns the script's supported distros in the state the user would have entered them.

        Example: "distro:arch:arch, distro:arch:arch".
        """

        distros = {}
        for distro in self.supported_distros:
            if distro.distro_name not in distros.keys():
                distros[distro.distro_name] = []

            distros[distro.distro_name].append(distro.architecture_name)

        distro_strings = []
        for distro in distros:
            distro_strings.append(f'{distro}:{":".join(distros[distro])}')

        return ', '.join(distro_strings)

    def add_function_matcher(self, content: str):
        """Adds the action to function matcher to the given content."""
        matcher = '\n'
        actions = self.actions

        shell = Shell.get_shell_by_name(self.shell)

        if shell.function_matcher_start is not '':
            matcher += f'{shell.function_matcher_start}\n\n'
        
        for action in actions:
            matcher += f'{shell.function_matcher_block}\n'.replace(
                '<action>', action.name
            )
        matcher += f'{shell.function_matcher_end}\n'

        matcher = matcher.replace(
            '<actions>',
            ' '.join([action.name for action in actions]),
        )
        
        return content + matcher
    
    def complete_content(self):
        """
        Adds the stuff to the script's content to make it working, returns the content.
        """
        with self.open_content() as f:
            new_content = f.read()

        shell = Shell.get_shell_by_name(self.shell)

        #adds the shebang
        shebang = f'#!{shell.interpreter_path} {shell.interpreter_arg}\n\n'
        new_content = shebang + new_content

        if self.use_default_function_matcher:
            new_content = self.add_function_matcher(new_content)

        return new_content

    def get_supported_actions(self):
        """Get the actions the script supports in a list."""
        return [action.name for action in self.actions]


class Action(BaseModel):
    """A model for storing an action that an app script supports."""

    name = CharField(255)
    script = ForeignKeyField(Script, backref='actions', on_delete='CASCADE')

    @classmethod
    def create_from_list(cls, script: Script, actions: list[str]):
        """Creates multiple action objects from a list."""
        action_objects = []
        
        for action in actions:
            action_objects.append(Action.create(name=action, script=script))

        return action_objects

src/installies/forms/base.py
from installies.validators.base import ValidationError

class FormInput:
    """
    A class for storing data about inputs from forms.

    :param name: The name of the input in the post data.
    :param validator: The validator class to validate the data.
    :param converter: A callable to convert the data to it's required type.
    :param default: The default value of the input.
    :param original_data_getter: A callable that should take a model object,
    and return the value of the attribute that the input is for. This is form
    edit forms.
    """

    def __init__(
            self,
            name: str,
            validator=None,
            converter=None,
            default=None,
            original_data_getter=None,
            script_form_input=False
    ):
        self.name = name
        self.validator = validator
        self.converter = converter
        self.default = default
        self.original_data_getter = original_data_getter

    def get(self, form: dict):
        """
        Gets the data and converts it with the converter.

        :param form: The data sent by the user.
        """

        data = form.get(self.name, self.default)

        if self.converter is not None:
            data = self.converter(data)

        return data    
        
    def validate(self, data):
        """
        Validate the data with the validator of the class.
        """
        if self.validator is None:
            return True

        if type(data) == list or type(data) == tuple:
            return self.validator.validate_many(data)
        
        return self.validator.validate(data)


class Form:
    """
    A base class for getting and validating data from forms submitted by the user.

    To add inputs to the form you can use the `inputs` attributes. To validate the data you
    can use the is_valid method. If the form is not valid, the error will be put in the error
    attribute. You can also add a model to the form that is created with the ``save`` method.
    By default the ``save`` method calls the model's create method with the arguments being the
    form data.

    :param form_data: A dictionary with all the form data from the user.
    :param original_object: If a form is for editing an object, you can
                            set an original object to ignore the validator
                            if the values are equal.
    """

    inputs = []
    model = None
    edit_form = False

    def __init__(self, form_data: dict, original_object = None):
        self.raw_form_data = form_data
        self.original_object = original_object
        self.error = None

        data = {}
        for inp in self.inputs:
            try:
                data[inp.name] = inp.get(self.raw_form_data)
            except ValueError:
                self.error = f'{inp.name} is not correct type.'

        self.data = data

    def is_valid(self):
        """Checks if the form is valid."""

        # returns false if there was an error getting the data
        if self.error is not None:
            return False

        for inp in self.inputs:
            # does not validate input the value hasnt changed changed.
            if (
                    self.edit_form and
                    inp.original_data_getter is not None and
                    self.original_object is not None and
                    inp.original_data_getter(self.original_object) == self.data[inp.name]
            ):
                continue;
            
            try:
                inp.validate(self.data[inp.name])
            except ValidationError as e:
                self.error = str(e)
                return False

        return True

    def save(self):
        """Creates the model in the ``model`` attribute."""
        if self.model is not None:
            return self.model.create(**self.data)

src/installies/forms/script.py
from flask import g
from installies.forms.base import Form, FormInput
from installies.validators.script import (
    ScriptActionValidator,
    ScriptShellValidator,
    ScriptDistroValidator,
    ScriptContentValidator,
    ScriptDistroDictionaryValidator,
    ScriptDescriptionValidator,
    ScriptVersionValidator,
)
from installies.models.supported_distros import SupportedDistro
from installies.models.app import App
from installies.models.script import Script


class ModifyScriptForm(Form):
    """
    A form for adding or editing app scripts.
    """

    inputs = [
        FormInput(
            'script-actions',
            ScriptActionValidator,
            lambda action_string: [x.strip() for x in action_string.split(',')],
            default='',
        ),
        FormInput(
            'script-shell',
            ScriptShellValidator,
        ),
        FormInput(
            'script-supported-distros',
            ScriptDistroDictionaryValidator,
            SupportedDistro.get_dict_from_string,
            '',
        ),
        FormInput('script-content', ScriptContentValidator),
        FormInput(
            'script-description',
            ScriptDescriptionValidator,
            original_data_getter=lambda script: script.description,
        ),
        FormInput('for-version', ScriptVersionValidator, default=None),
        FormInput('script-use-default-function-matcher', default=None),
    ]
    model = Script


class CreateScriptForm(ModifyScriptForm):
    """A form for creating Scripts."""

    model = Script
    
    def save(self, app: App):
        script = Script.create(
            content=self.data['script-content'],
            shell=self.data['script-shell'],
            description=self.data['script-description'],
            submitter=g.user,
            app=app,
            version=self.data['for-version'],
            actions=self.data['script-actions'],
            use_default_function_matcher=(True if self.data.get('script-use-default-function-matcher') is not None else False),
        )

        distros = SupportedDistro.create_from_dict(script, self.data['script-supported-distros'])

        return script


class EditScriptForm(ModifyScriptForm):
    """A form for editing Scripts."""

    edit_form = True
    
    def save(self, script: Script):
        for distro in script.supported_distros:
            distro.delete_instance()
        
        SupportedDistro.create_from_dict(
            script,
            self.data['script-supported-distros']
        )
        
        return script.edit(
            shell=self.data['script-shell'],
            content=self.data['script-content'],
            description=self.data['script-description'],
            version=self.data['for-version'],
            use_default_function_matcher=(True if self.data.get('script-use-default-function-matcher') is not None else False),
            actions=self.data['script-actions'],
        )

src/installies/apps/app_library/views.py
from flask import render_template, Blueprint, request, g, Response
from installies.lib.view import TemplateView
from installies.apps.app_manager.groups import AppGroup
from installies.apps.app_manager.models import App
from peewee import *

app_library = Blueprint('app_library', __name__)

class IndexView(TemplateView):
    template_path = 'index.html'

app_library.add_url_rule('/', 'index', view_func=IndexView.as_view())
    
@app_library.route('/apps')
def apps():
    apps = AppGroup.get(**request.args).where(App.visibility == 'public')
    
    return render_template('apps.html', apps=apps)

src/installies/templates/app_table.html
<table class="max-width">
    <thead>
      <tr class="underline">
        <th>Name</th>
        <th>Creation Date</th>
        <th>Last Modified</th>
        <th>Description</th>
        <th>Current Version</th>
        <th>Submitter</th>
        <th>Maintainers</th>
      </tr>
    </thead>
    <tbody>
      {% for app in apps %}
      <tr class="underline">
        <td><a href="{{ url_for('app_manager.app_view', app_name=app.name) }}" >{{ app.name }}</a></td>
	<td>{{ app.creation_date.strftime('%d-%m-%Y %H:%M') }} (UTC)</td>
	<td>{{ app.last_modified.strftime('%d-%m-%Y %H:%M') }} (UTC)</td>
        <td>{{ app.description }}</td>
        <td>{{ app.current_version }}</td>
        <td><a href="{{ url_for('auth.profile', username=app.submitter.username) }}">{{ app.submitter.username }}</a></td>
        <td>
	  {% for maintainer in app.maintainers.get_maintainers() %}
         <a class="link" href="{{ url_for("auth.profile", username=maintainer.user.username) }}">{{ maintainer.user.username }}</a>{% if app.can_user_edit(g.user) %}{% endif %}{% if loop.index != app.maintainers.get_maintainers()|length %}, {% endif %}
         {% endfor %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
</table>

src/installies/templates/apps.html
{% extends "base.html" %}

{% block title %}Apps{% endblock %}

{% block body %}
<div class="container black" style="max-width: 1200px">
  <h2>Refine Apps</h2>
  
  <form action="{{ url_for('app_library.apps') }}" method="get">
    <fieldset>
      <div>
	<label for="search-in">Search In:</label>
	<select name="search-in" id="search-in">
	  <option value="name" {% if request.args.get('search-in') == 'name' %}selected=""{% endif %}>Name</option>
	  <option value="description" {% if request.args.get('search-in') == 'description' %}selected=""{% endif %}>Description</option>
	  <option value="name, description" {% if request.args.get('search-in') == 'name, description' %}selected=""{% endif %}>Name and Description</option>
	  <option value="maintainers" {% if request.args.get('search-in') == 'maintainers' %}selected=""{% endif %}>Maintainers</option>
	  <option value="submitter" {% if request.args.get('search-in') == 'submitter' %}selected=""{% endif %}>Submitter</option>
	</select>
      </div>
      <div>
	<label for="keywords">Keywords:</label>
	<input type="text" name="k" id="keywords" value="{{ request.args.get('k', '') }}">
      </div>
      <div>
	<label for="supports">Supports:</label>
	<input type="text" name="supports" id="supports" value="{{ request.args.get('supports', '') }}">
      </div>
      <div>
	<label for="sort-by">Sort By:</label>
	<select name="sort-by" id="sort-by">
	  <option value="name" {% if request.args.get('sort-by') == 'name' %}selected=""{% endif %}>Name</option>
	  <option value="description" {% if request.args.get('sort-by') == 'description' %}selected=""{% endif %}>Description</option>
	  <option value="creation_date" {% if request.args.get('sort-by') == 'creation_date' %}selected=""{% endif %}>Creation Date</option>
	  <option value="last_modified" {% if request.args.get('sort-by') == 'last_modified' %}selected=""{% endif %}>Last Modified</option>
	  <option value="submitter" {% if request.args.get('sort-by') == 'submitter' %}selected=""{% endif %}>Submitter</option>
	</select>
      </div>
      <div>
	<label for="order-by">Order By:</label>
	<select name="order-by" id="order-by">
	  <option value="asc" {% if request.args.get('order-by') == 'asc' %}selected=""{% endif %}>Ascending</option>
	  <option value="desc" {% if request.args.get('order-by') == 'desc' %}selected=""{% endif %}>Descending</option>
	</select>
      </div>
      <div>
	<label for="page">Page:</label>
	<input type="text" name="page" id="page" size="4" value="{{ request.args.get('page', 1) }}">
      </div>
      <div>
	<label for="per-page">Per Page:</label>
	<input type="text" name="per-page" id="per-page" size="2" value="{{ request.args.get('per-page', 10) }}">
      </div>
      <div>
	<input type="submit" value="Go" class="button">
      </div>
    </fieldset>
  </form>
</div>

<div class="container black" style="max-width: 1200px">
  <p class="no-margin">{{ total_app_count }} app{% if total_app_count != 1 %}s{% endif%} found. Page {{ request.args.get('page', '1') }} of {{ page_count }}.</p>
  {% if apps|length == 0 %}
  <p class="no-margin">No Apps Found</p>
  {% else %}
  {% include "partials/app/table.html" %}
  {% endif %}
</div>

{% set url_for_route = 'app_library.apps' %}
{% set url_for_arguments = {} %}
{% include "partials/pager.html" %}

{% endblock %}

src/installies/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=yes">
    {% block extra_meta %}
    {% endblock %}
    <title>{% block title %}{% endblock %} - Installies</title>
    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/static/css/style.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.js" integrity="sha512-8RnEqURPUc5aqFEN04aQEiPlSAdE0jlFS/9iGgUyNtwFnSKCXhmB6ZTNl7LnDtDWKabJIASzXrzD0K+LYexU9g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.css" integrity="sha512-uf06llspW44/LZpHzHT6qBOIVODjWtv4MxCricRxkzvopAlSWnTf6hpZTFxuuZcuNE9CBQhqE0Seu1CoRk84nQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/monokai.min.css" integrity="sha512-R6PH4vSzF2Yxjdvb2p2FA06yWul+U0PDDav4b/od/oXf9Iw37zl10plvwOXelrjV2Ai7Eo3vyHeyFUjhXdBCVQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/shell/shell.min.js" integrity="sha512-HoC6JXgjHHevWAYqww37Gfu2c1G7SxAOv42wOakjR8csbTUfTB7OhVzSJ95LL62nII0RCyImp+7nR9zGmJ1wRQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% block header %}
    {% endblock %}
</head>
<body>
  {% include "partials/nav.html" %}

  {% with errors = get_flashed_messages(category_filter=["error"]) %}
  {% if errors %}
  {% for msg in errors %}
  <div class="container red">
    <h3 class="red">Error!</h3>
    <p class="container-description red">{{ msg }}</p>
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  
  {% with errors = get_flashed_messages(category_filter=["success"]) %}
  {% if errors %}
  {% for msg in errors %}
  <div class="container green">
    <h3 class="green">Success!</h3>
    <p class="container-description green">{{ msg }}</p>
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  
  {% block body %}
  {% endblock %}

  {% include "partials/footer.html" %}
</body>
</html>

src/installies/templates/create_app.html
{% extends "base.html" %}

{% block title %}Create an App{% endblock %}

{% block body %}
<div class="container black" style="width:500px">
    <h2>Create an App</h2>

    {% set form_url = url_for('app_manager.create_app') %}
    {% set show_app_name_input = 'not false' %}
    {% include "app/app_editor.html" %}
</div>
{% endblock %}

src/installies/templates/forgot_password.html
{% extends "base.html" %}

{% block title %}Forgot Password{% endblock %}

{% block body %}
<div class="container black" style="width:500px">
    <h2>Forgot Password</h2>
    <p>Please enter the email of the account you wish to change the password of. You will
    be sent an email with a link to reset your password.</p>

    <form action="{{ url_for('auth.forgot_password') }}" method="post">
      <div class="form-input-container">
	<label for="email">Email</label><br>
	<input type="email" name="email" class="textbox" required><br>
      </div>
      
      <div class="form-input-container">
	<input type="submit" value="Submit" class="button">
      </div>
    </form>
</div>
{% endblock %}

src/installies/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block header %}
{% endblock %}

{% block body %}
<div class="container" style="max-width:1400px;">
    <h3>Welcome to installies!</h3>
    <p class="container-description">
      Installies is a site for managing, organizing, and retrieving shell scripts for use to install, remove, update or compile apps on Linux and Unix-based systems. To get started you can <a href="https://docs.installies.org">read the docs</a>.
    </p>
</div>
{% if g.is_authed %}
<div class="container black" style="max-width:1400px">
  <h2>My Apps</h2>
  {% if user_maintained_apps|length == 0 %}
  <p class="no-margin">You maintain no apps.</p>
  {% else %}
  {% set apps = user_maintained_apps %}
  {% include "partials/app/table.html" %}
  {% endif %}
  <a href="{{ url_for('app_library.apps', **{'search-in':'maintainers','k':g.user.username}) }}">Search for apps I maintain</a>
</div>

<div class="container black" style="max-width:1400px">
  <h2>My Scripts</h2>
  {% if user_maintained_scripts|length == 0 %}
  <p class="no-margin">You maintain no scripts.</p>
  {% else %}
  {% set show_script_app = True %}
  {% set scripts = user_maintained_scripts %}
  {% include "partials/script/table.html" %}
  {% endif %}
  <a href="{{ url_for('app_library.scripts', **{'search-in':'maintainers','k':g.user.username}) }}">Search for scripts I maintain</a>
</div>
{% endif %}

<div class="container" style="max-width:1400px">
  <h3>Recently Updated Apps</h3>
  {% set apps = recently_updated_apps %}
  {% include "partials/app/table.html" %}
  <a href="{{ url_for('app_library.apps', **{'sort-by':'last_modified'}) }}">Search for more</a>
</div>

<div class="container" style="max-width:1400px">
  <h3>Newest Apps</h3>
  {% set apps = newest_apps %}
  {% include "partials/app/table.html" %}
  <a href="{{ url_for('app_library.apps', **{'sort-by':'creation_date'}) }}">Search for more</a>
</div>
{% endblock %}

src/installies/templates/login.html
{% extends "base.html" %}

{% block title %}Log In{% endblock %}

{% block body %}
<div class="container black auto-margin" style="width:450px;">
  <h2>Log In</h2>
  <h5 class="grey">Or if you don't have an account, <a class="link" href="/signup">Sign Up</a></h5>

    <form action="{{ url_for('auth.login') }}{% if 'referer' in request.args.keys() %}?referer={{ request.args['referer'] }}{% endif %}" method="post">
        <div class="form-input-container">
            <label for="username" >Username</label><br>
            <input type="text" name="username" id="username" class="textbox wide-textbox" required><br>
        </div>
        
        <div class="form-input-container">
            <label for="password">Password</label><br>
            <input type="password" name="password" id="password" class="textbox wide-textbox" required><br>
        </div>
        
        <div class="form-input-container inline">
          <input type="submit" value="Submit" class="button inline">
        </div>
        
    </form>

    <h5><a class="link" href="/forgot-password">Forgot Password?</a></h5>
</div>
{% endblock %}

src/installies/templates/profile.html
{% extends "base.html" %}

{% block title %}{{ user.username }}'s Profile{% endblock %}

{% block body %}
    <div class="container" style="width:800px;">
        <h2>{{ user.username }}'s Profile{% if user.is_banned() %} <span class="red">[BANNED]</span>{% endif %}</h2>
        
        <table>
	  {% if g.user.admin %}
	  <tr>
	    <th>Options:</th>
            <td>{% if user.is_banned() %}[<a href="{{ url_for('admin.unban_user', username=user.username) }}">Unban</a>]{% else %}[<a class="red" href="{{ url_for('admin.ban_user', username=user.username) }}">Ban</a>]{% endif %}</td>
	  </tr>
	  {% endif %}
          <tr>
            <th>Join Date:</th>
	    <td>{{ user.creation_date.strftime('%d-%m-%Y %H:%M') }} (UTC)</td>
          </tr>
	  {% if user.is_banned() %}
	  <tr>
            <th>Ban Reason:</th>
            <td>{{ user.bans[0].reason }}</td>
          </tr>
	  {% endif %}
	  <tr>
	    <th>Links:</th>
	    <td>
	      <ul class="no-margin no-padding no-list-style-type">
		<li><a href="{{ url_for('app_library.apps', **{'search-in':'maintainers','k':user.username}) }}">View this user's apps</a></li>
		<li><a href="{{ url_for('app_library.scripts', **{'search-in':'maintainers','k':user.username}) }}">View this user's scripts</a></li>
		</ul>
	    <td>
	  </tr>
        </table>
    </div>
{% endblock %}

src/installies/templates/reset_password.html
{% extends "base.html" %}

{% block title %}Reset you Password{% endblock %}

{% block body %}
<div class="container black" style="width:500px">
    <h2>Reset your Password</h2>

    <form action="{{ url_for('auth.reset_password', token=token) }}" method="post">
      <div class="form-input-container">
	<label for="password">Password</label><br>
	<input type="password" name="password" class="textbox" required><br>
      </div>

      <div class="form-input-container">
	<label for="password-confirm">Confirm Password</label><br>
	<input type="password" name="password-confirm" class="textbox" required><br>
      </div>
      
      <div class="form-input-container">
	<input type="submit" value="Submit" class="button">
      </div>
    </form>
</div>
{% endblock %}

src/installies/templates/scripts.html
{% extends "base.html" %}

{% block title %}Scripts {% endblock %}


{% block body %}
<div class="auto-margin" style="max-width: 1400px">
{% set url_for_route = 'app_library.scripts' %}
{% include "partials/script/refiner.html" %}

<div class="container black">
{% set show_script_app = True %}
{% include "partials/script/table.html" %}
</div>

{% set url_for_route = 'app_library.scripts' %}
{% include "partials/pager.html" %}
</div>
{% endblock %}